- index.html
- main.css
Added static html layout to be used in all pages
> created a basic page layout

- index.html
Created Nav Bar with:
four buttons
each button linked to the four pages
> navbar with four buttons linked to corresponding pages

- index.html
Added Footer for basic html layout
> Footer for basic html layout

- repositories.html
Added repositories.html
Added repositories.html
Added hard coded list of repo cards
Added form to submit new repos. 
fixes #9 #10 #23 #18 #16 
Adds new page for repositories, and the boilerplate for a form to dynamically add new repositories. 
hs -o, click on 'Repositories' in navbar. Repos should be populated in data container, and the form should be rendered below.
> Added repositories.html

- index.html
- main.css
> Jr pinned repo card

- projects.html
Added Projects page
Fixes  #15 and #20
Needed for MVP
Use Navbar to get there and visually confirm layout
html added to projects.html
> added projects page with cards and form

- packages.html
Created packages.html
Added Entry form
Modified cards slightly
Fixes #19 
Fixes #14 
Fixes #47 
Gives ability to enter data and put them somewhere
Form is added and cards are placed and smaller than cards previously used.
- [x ] New feature (non-breaking change which adds functionality)
> created packages html with form and cards

- main.js
JS Structuring with comments 
Added in comments to main.js that create the codebase structure for JavaScript. 
Will keep the team on the same codebase and structure. 
hs -o, load main.js, code functions within appropriate areas.
> Added comment structure for JS

- main.js
Added printToDom function
fixes #35
> printToDom

- main.js
Core User Data Structure
Added Data Type for User data to be utilized in JS functions. 
fixes #4
fixes #25 
The core data will be utilized across all 4 HTML pages and DOM manipulation. 
hs -o, load main.js. Core user data is within data type comment section. 
User data
> Cw data type

- index.html
- main.js
Added function for accept form input and building pinned repos page
> Jr pinned repo builder

- main.js
- packages.html
Created function to build packages form
Fixed init function to make sure it runs on separate pages
Fixes #28 
- [x ] Bug fix (non-breaking change which fixes an issue)
> Cm build packages

- main.js
- repositories.html
Created a JS function to build Repos
Added a feature to build repos in repositories.html
fixes #32
Adds dynamic functionality that builds array of Repos on Repos page.
hs -o, click on the link to Repos on navbar. Array of 4 placeholder repos should be present on DOM.
> HTML - Repo Builder

- main.js
- projects.html
Added final builder function changes
fixes # 30
Need a function that will dynamically add array of projects to Project link
hs -o, click link to projects and check that projects render on DOM.
> Ts js functions

- index.html
- main.css
- main.js
Added a form that lets you add repos that are automatically pinned
> Added form and dynamic tag buttons

- main.js
Fixes bug in Pinned Repos form
Pinned repo form created bug on other 3 pages, fixed that to only add event listener on relevant page. 
Fixes bug 27
Need functional form across 4 pages, without bugs. 
hs -o, load overview page, test form. Load other links on navbar, ensure filler data renders in data form.
> bug fix pinned repo form

- main.js
Added dynamic repo tags
Loops through array of repo tags, renders within each repo card. 
fixes #31 
Need dynamic tags for each repo.
hs -o, click Repos link on navbar, check that tags on each card are dynamic.
> Added dynamic repo tags

- index.html
- main.css
- main.js
Added a button to delete pinned repositories.
Fetch branch
Add multiple pinned repositories through the form. Delete them in varying orders.
> Jr delete pinned repo button

- main.js
- projects.html
1. Added search bar to Projects page. Searches/filters to show projects that contain letters typed.
2. fixed comments in JS.
3. Fixed description field to match other pages, be "optional" and to print "No description" if field is left empty.
4. Small styling to match other pages and wireframe.
fixes #40 
stretch feature
fetch ts-sort-projects
on Projects page, type in search bar and watch the magic
> Projects page search bar

- main.css
- main.js
Fixed the bug where you had to click twice in the profile section to get about me to open.
Formatted JS file as well.
> Jr about me fix

- main.js
- packages.html
Ability to search packages
#39 
STRETCH Goal to create functional search
Search packages by typing in the search bar
- [X ] New feature (non-breaking change which adds functionality)
> functional search bar

- main.css
- main.js
- repositories.html
Added a Star Toggler to the Repo Page
User can now star Repos in Repositories page by clicking on the star icon. 
fixes #43 
Users will now have the ability to star repos that hold more important or significance. 
hs -o, click repositories in navbar. 
Each repo has a star in the header, if functional the star should fill in gold when clicked.
> Repo Star Feature 

- index.html
- main.css
- main.js
- packages.html
- projects.html
- repositories.html
Added CSS styling 
Started Color Palette for CSS styling 
#51 
Makes site styled more user friendly. 
hs -o, check background and font colors.
> Background styling

- main.css
- main.js
- projects.html
Added sort feature for Projects page. 
Can now sort by Name (alphabetically), by Date (Oldest first) or by Date (Newest first).
fixes #41 
Stretch feature for project.
Fetch and navigate to Projects page. click on sort drop down and sort.
Try to add new projects to include in sort.
- [X ] New feature (non-breaking change which adds functionality)
> Ts sort project
